Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - db/**/*
    - config/**/*
    - bin/**/*
    - spec/**/*
    - test/**/*
    - app/views/**/*
    - config.ru

Metrics/AbcSize:
  IgnoredMethods:
    - 'finance_info'